package Acme::CPANLists::Import::PerlDancerAdvent::2016_12_10;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2016/10] (retrieved on 2017-01-31). Visit the URL for the full contents.",entries=>[{module=>"Dancer2::Logger::LogReport"},{module=>"Dancer2::Plugin::LogReport"},{module=>"Log::Report"},{module=>"Log::Report::DBIC::Profiler"},{module=>"Log::Report::Dispatcher::Syslog"},{module=>"Log::Report::Translator"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2016 (day 10)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2016 (day 10)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2016/10> (retrieved on 2017-01-31). Visit the URL for the full contents.

