package Acme::CPANLists::Import::PerlDancerAdvent::2016_12_01;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2016/1] (retrieved on 2017-01-31). Visit the URL for the full contents.",entries=>[{module=>"HTTP::Headers::Fast"},{module=>"HTTP::XSCookies"},{module=>"HTTP::XSHeaders"},{module=>"JSON"},{module=>"JSON::MaybeXS"},{module=>"Plack::Request"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2016 (day 1)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2016 (day 1)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2016/1> (retrieved on 2017-01-31). Visit the URL for the full contents.

