package Acme::CPANLists::Import::PerlDancerAdvent::2016_12_19;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2016/19] (retrieved on 2017-01-31). Visit the URL for the full contents.",entries=>[{module=>"Dancer2"},{module=>"Dancer2::Core::Role::SessionFactory::File"},{module=>"Dancer2::Plugin::Auth::Extensible"},{module=>"Dancer2::Session::JSON"},{module=>"Dancer2::Session::YAML"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2016 (day 19)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2016 (day 19)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2016/19> (retrieved on 2017-01-31). Visit the URL for the full contents.

