package Acme::CPANLists::Import::PerlDancerAdvent::2016_12_14;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2016/14] (retrieved on 2017-01-31). Visit the URL for the full contents.",entries=>[{module=>"HTTP::Headers"},{module=>"HTTP::Headers::Fast"},{module=>"HTTP::XSHeaders"},{module=>"JSON"},{module=>"Plack"},{module=>"Plack::Middleware::Cache"},{module=>"YAML"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2016 (day 14)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2016 (day 14)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2016/14> (retrieved on 2017-01-31). Visit the URL for the full contents.

