package Acme::CPANLists::Import::PerlDancerAdvent::2016_12_08;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2016/8] (retrieved on 2017-01-31). Visit the URL for the full contents.",entries=>[{module=>"Gazelle"},{module=>"Plack"},{module=>"Plack::Loader::Shotgun"},{module=>"Plack::Middleware::Refresh"},{module=>"Starman"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2016 (day 8)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2016 (day 8)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2016/8> (retrieved on 2017-01-31). Visit the URL for the full contents.

