package Acme::CPANLists::Import::PerlDancerAdvent::2016_12_12;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2016/12] (retrieved on 2017-01-31). Visit the URL for the full contents.",entries=>[{module=>"AnyEvent"},{module=>"App::FatPacker"},{module=>"CGI"},{module=>"CGI::Deurl::XS"},{module=>"Class::XSAccessor"},{module=>"Config::Any"},{module=>"Cpanel::JSON::XS"},{module=>"Crypt::URandom"},{module=>"EV"},{module=>"HTTP::Parser::XS"},{module=>"HTTP::XSCookies"},{module=>"JSON"},{module=>"JSON::MaybeXS"},{module=>"JSON::XS"},{module=>"Math::Random::ISAAC::XS"},{module=>"Moo"},{module=>"Plack"},{module=>"Return::MultiLevel"},{module=>"Scope::Upper"},{module=>"URL::Encode"},{module=>"URL::Encode::XS"},{module=>"YAML::XS"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2016 (day 12)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2016 (day 12)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2016/12> (retrieved on 2017-01-31). Visit the URL for the full contents.

