package Acme::CPANLists::Import::PerlDancerAdvent::2016_12_20;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2016/20] (retrieved on 2017-01-31). Visit the URL for the full contents.",entries=>[{module=>"Dancer2::Plugin::SendAs"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2016 (day 20)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2016 (day 20)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2016/20> (retrieved on 2017-01-31). Visit the URL for the full contents.

