package Acme::CPANLists::Import::PerlDancerAdvent::2016_12_23;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2016/23] (retrieved on 2017-01-31). Visit the URL for the full contents.",entries=>[{module=>"DBI"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2016 (day 23)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2016 (day 23)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2016/23> (retrieved on 2017-01-31). Visit the URL for the full contents.

